/** Each paragraph for the About component*/

export const aboutP1 = "I’m a software engineer and former higher education professional. I decided to make a career change after spending several months getting up at 4:30am each day to teach myself JavaScript before going to work. In March 2020 I enrolled at Rithm School, a full stack web development program in San Francisco, and have since interned as a software engineer at CleverCounsel, and worked as a teaching assistant at Rithm School."

export const aboutP2 = "CleverCounsel is a legal services software company where I had the opportunity to design, build, and test new features, as well as implement solutions for reported bugs. My favorite accomplishment of the internship was designing and building the password reset feature, giving users the ability to request a link to reset a forgotten password. I really enjoyed taking this seemingly simple feature and breaking it into small programmable tasks while discovering its complexities along the way, researching new technologies, and getting to design the end to end functionality. This build consisted of multiple backend endpoints, email integration and cryptographic hashes, form validation, frontend React components, and integration tests. (technologies/tools included Python, Flask, Flask-Mail, JavaScript, React, itsdangerous, WTForms, and AWS Simple Email Service)"

export const aboutP3 = "I particularly love debugging and really thinking through scenarios that put a feature/application to the test. Having been on the client side of the table, I have first hand experience of what it's like to have a feature moved to production, only to discover it works for most scenarios, but not others. As a result, I came to understand the importance of knowing and accounting for your edge cases and remaining aware of the outlier scenarios that are important to the overall success of a new feature."

export const aboutP4 = "Prior to making the transition to software engineering, my career in higher education began at a small art and design college in Florida, where over the course of six years I worked my way up from a loan coordinator to the director of student financial services."

export const aboutP5 = "My interest in software engineering began at UC Berkeley where I managed the Federal Work-Study Program administered by the Financial Aid and Scholarships Office. While my expertise was financial aid, a couple campus transitions to new software systems led to frequent collaboration with business analysts and developers, as we discussed needs of the program and issues/ bugs with the newly implemented software. This was my first introduction to whiteboarding and I quickly learned how much I enjoyed the problem solving process and through this collaboration, I also developed an interest in the technical side of the program. At this point I began teaching myself JavaScript and right away I was hooked! Several months later I made the decision to make a career change."

export const aboutP6 = "I’m currently a teaching assistant for a full stack web development program. In this role I support lead instructors in educating students with a curriculum that includes advanced JavaScript concepts, server-side programming with Python, automated testing, database management, web security, and single page applications with React. My support consists of live code reviews with feedback, coaching students on coding principles and best practices, grading technical assessments, and assisting with designing new assignments and updating curriculum."

export const aboutP7 = "My experience with technologies consists of JavaScript (including vanilla, jQuery, React), HTML, CSS (including Bootstrap) on the frontend, JavaScript (Node/Express) and Python (Flask) on the backend, Jest and Jasmine for JavaScript testing, doctest and unittest for Python testing, and PostgreSQL as well as MySQL databases. I have really enjoyed learning all the technologies I’ve been exposed to so far and I’m excited to continue learning more throughout my career."